### PR TITLE
Resolve CURIEs passed to createNamedNode() factory methods.

### PR DESCRIPTION
**Pull request by ckristo**
PR for issue #62

### CODE REVIEW

**Comment by ckristo** [comment]
Tests are running fine here.. will look at the failing Travis build tomorrow..

**Comment by ckristo** [comment]
hm, works for me with node 0.12.12 also ... any idea what could go wrong on Travis?

**Comment by ckristo** [comment]
Ok, it seems to be a problem with the cyclic dependency between (1) rdf-ext -> rdf-test-data -> (2) rdf-ext. When stepping through the test code, it seems that code from (2) is executed, which is a copy of the original (unmodified) code.

@bergos do you know how to (properly) fix this so that the Travis build does not fail?

BR,

**Comment by bergos** [comment]
Sorry, I didn't have time until now.

Strange, works for me with the same node and npm version as travis uses without symlink. Also I had a look at the existing code in environment.js and I have seen some code fragments I don't like. It should be possible to use .resolve() for this use case. I will clean up the code and integrate your patch. Maybe it's working after that code cleanup.

**Comment by bergos** [comment]
I cleaned up the [CURIE code](https://github.com/rdf-ext/rdf-ext/pull/66) a little bit.

Also I thought about the .resolve() in the .createNamedNode() method. We discussed [IRI validation](https://github.com/rdfjs/representation-task-force/issues/57) in the last representation TF meeting. I don't like IRI validation, because this could limit the usage of the model classes. I'm not sure, but maybe calling .resolve() could limit us also in some way. But if people start using that feature, it's hard to remove it later. Another argument against IRI validation was the cost. Parsing really big files would benefit from fast factory methods. Calling .resolve() everytime would slowdown the factory. Usually it's known if a string contains a CURIE or an IRI. Also with the code cleanup PR, it should be easier to try resolving a CURIE. Now I think it would be better to not implement that feature.

**Comment by ckristo** [comment]
@bergos regarding performance: why not adding some kind of option (as argument) to disable auto-resolving CURIEs?

**Comment by bergos** [comment]
A different method would be better for the future, because the current .createNamedNode will become the .iri of the [RDFJS Representation TF spec](https://github.com/rdfjs/representation-task-force/blob/master/interface-spec.md#datafactory). There is also a [Data Model Extened](https://github.com/rdfjs/representation-task-force/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Data+Model+Extended%22) milestone and a [Create an interface to shrink and expand CURIEs](https://github.com/rdfjs/representation-task-force/issues/49) issue. Adding new features is very difficult at the moment  :-( I will propose adding end dates to the milestone to push these topics a little bit.

**Comment by bergos** [comment]
I expect prefix maps will be revisited soon in RDF/JS. So let's not introduce new features, which we have to align later to a spec. A separate package for prefix map utils functions would be a better option right now.

**Pull request closed without merging**
